### ISSUE TITLE
[GBC] Mr. Driller - Blocks are Invisible

### ISSUE THREAD

**Issue by JackWitherell** [MiSTer-devel/Gameboy_MiSTer#104]
After starting the normal game mode (2500m), all blocks are invisible and can't be seen.

![mdril](https://user-images.githubusercontent.com/4626546/94101882-a5401580-fde5-11ea-943f-a145936121e7.png)

Breaking through a few blocks to make some fall down and I get this, seems only moving blocks are visible. Everything else doesn't show.

![awodril](https://user-images.githubusercontent.com/4626546/94101886-a7a26f80-fde5-11ea-8a7e-eb8ab79dc4dc.png)

**Comment by wwark** [comment]
Which version of the rom did you use ?
Me I tried Mr. Driller (Japan) (NP).gbc and I don't reproduce the issue.

**Comment by JackWitherell** [comment]
USA version, I ripped it myself. I'll try finding it online and see if I can reproduce the issue and if not I'll try the JP version.

**Comment by JackWitherell** [comment]
Tried a version online and a jp version, still had the issue. Updated the core and it's all good now. I feel dumb. But good.
