### ISSUE TITLE
[GB] Super Mario Land sound issue 

### ISSUE THREAD

**Issue by cedrik9456** [MiSTer-devel/Gameboy_MiSTer#105]
I've recently finished this game for the first time on Mister and noticed that when I enter the pipes the music gets _much_ louder than in the overworld. Also, I may be wrong but I believe that the final boss "loading" music is slightly off.

**Comment by maij** [comment]
Can't reproduce.

**Comment by sorgelig** [comment]
old issue. probably already fixed.
