### ISSUE TITLE
[GB] Tenjin Kaisen (Japan)

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#108]
@paulb-nl, for information with this commit (https://github.com/MiSTer-devel/Gameboy_MiSTer/commit/5fd81a5ae0baf9db135cdb8ca2eff252c92fcec8), you have this new issue with this game "Tenjin Kaisen (Japan)" on GB Mode. 

This issue is not present on GBC mode with this commit. 
In the current release of Gameboy core, the issue is not present on GB Mode and GBC Mode
![IMG_20201129_114202](https://user-images.githubusercontent.com/469461/100539652-3c877600-3238-11eb-9fdd-ab40fe66064a.jpg)
.
Thanks,

**Comment by paulb-nl** [comment]
Thanks Marc, the problem was the sprites not being cleared after disabling sprites. Will be fixed soon.

**Comment by wwark** [comment]
Fixed with (https://github.com/MiSTer-devel/Gameboy_MiSTer/commit/1fb2a93d152bf49b6f1823abb33e868ccdc1605f) thanks @paulb-nl !
