### ISSUE TITLE
[GBC] Magical Chase GB - Minarai Mahoutsukai Kenja no Tani e (Japan) - Glitches

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#112]
Information Rom (Sha1sum) : 3b13fc974d68a8b057ab8133a0ba7e3fbac23f11

In the first level, you will find glitches on the top of the ramparts of the towers.
On the second level, you will find glitches on the top of the floor.

Those glitches are not present on my GBA SP (GBC mode).

Thanks,

**Comment by paulb-nl** [comment]
I found a video of real Gameboy Advance hardware [https://youtu.be/n8JKs9kvHI4?t=75](https://youtu.be/n8JKs9kvHI4?t=75) 

It looks like real hardware also has some glitches but much less than the Gameboy core. Though that video is 30fps and I haven't found a good 60fps video of real hardware.

**Comment by wwark** [comment]
Thank you @paulb-nl for pointing to this yt video :+1: 

Yes for the glitches on first level are not noticeable on the screen of GBA SP but they are present in this video done by a capture.

I made more run for the second level and I saw one time the glitches on the top of the floor (on GBA SP) when there is a lot of opponents.

So i close this ticket.
