### ISSUE TITLE
Mortal Kombat 1/2 cartridge: selected game won't start

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Gameboy_MiSTer#116]
core version: 201204

Mortal Kombat 1/2 cart (both USA and JAP versions) boots but once the game is selected it just reboots.

![20201216_190758-Mortal Kombat   Mortal Kombat II (Japan)](https://user-images.githubusercontent.com/1863036/102394729-74354280-3fda-11eb-9acb-e0930e27cb60.png)

**Comment by wwark** [comment]
It is the same issue as https://github.com/MiSTer-devel/Gameboy_MiSTer/issues/90
Thanks,

**Comment by wwark** [comment]
it is fixed in this PR https://github.com/MiSTer-devel/Gameboy_MiSTer/pull/117
This ticket can be closed.

**Comment by SegaSnatcher** [comment]
Yes this can be closed.
