### ISSUE TITLE
[GB/GBC] Zerd no Densetsu hangs in the first start

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#121]
The information of the ROM : sha1sum 8db8ad90505d9a2b4485e903b9f5d67bb9c0c149

How to reproduce the hangs
* start the core
* launch the rom "Zerd no Densetsu"
* The games start hangs and white screen
* Choose "Reset" and the game launch correctly
* Load again the game without restart the core, the hangs happens time to time

It happens on the version 20201204 and also in the version contains the fix of pinball fantasies
It happens in GB and GBC mode

Thanks,

**Comment by paulb-nl** [comment]
This game should not work because it requires the STAT IRQ bug but somehow it always works for me. I tried to load the game many times but it does not hang.

This time the game crashing would be a good thing :)

**Comment by birdybro** [comment]
I also just tested on latest build with everdrive pack matching rom, same result. It runs fine for me.

**Comment by wwark** [comment]
Thank you @paulb-nl. It is another edge case.

I do a quick search regarding the STAT IRQ Bug. 
In this website https://mgba.io/2017/05/29/holy-grail-bugs/, there is this statement: 
"The second glitch only occurs on the Game Boy, not on the Game Boy Color. When writing to the STAT register there are actually circumstances in which an interrupt will spuriously trigger without any of the STAT IRQ conditions being fulfilled. As with seemingly all obscure hardware bugs there are games that rely on this bug as well. A commonly cited game is Legend of Zerd (ザードの伝説, also known as Legend of Xerd or Zerd no Densetsu), which immediately crashes if the bug is not emulated. Likewise, the game will not run on a Game Boy Color since the bug was fixed."

So when STAT IRQ bug will be implemented, the hang will occur just on GBC Mode.

The reset mode and load rom without restart the core can have strange behaviour and they don't exist on real hardware. I see it time to time.

Do you know what are remains on Mister after a reset or a load rom without restart the core ?

**Comment by paulb-nl** [comment]
> Do you know what are remains on Mister after a reset or a load rom without restart the core ?

The RAM is not cleared. I have also seen some glitches with Fifa 96 for example if the RAM is not clear. 

Do you use any boot.rom with the core?

**Comment by SegaSnatcher** [comment]
I can't get this game to crash at all using the build with Pinball Fantasies fix.

**Comment by wwark** [comment]
I used boot0.rom for a custom palette and boot1.rom (for the original bios of GBC)

**Comment by wwark** [comment]
Do you think it is possible to clear the RAM ?

**Comment by paulb-nl** [comment]
Sure RAM clearing can be added.

Finally I was able to make the game crash. Somehow the game only crashes when the core boots with the original Game Boy Color bios.
1. Put boot1.rom with original GBC bios. 
2. Set system to Game Boy Color.
3. Save settings and reboot
4. Start the game and it will crash on Gameboy and Gameboy Color mode

Now I can test the STAT IRQ bug.

**Comment by wwark** [comment]
Thank you @paulb-nl !
We have the correct behavior now with this PR https://github.com/MiSTer-devel/Gameboy_MiSTer/pull/128.
GBC -> The game crash at the first load and also on reset
GB -> The game work correctly without crash.
I made my test with the original GBC bios.

**Comment by paulb-nl** [comment]
I think it now also crashes without original GBC bios. It changed after the save states were added. Maybe more things are cleared.

**Comment by SegaSnatcher** [comment]
Just saw the recent commit, again fantastic work Paul, you are the MVP.

**Comment by wwark** [comment]
Thanks @RobertPeip ! So maybe clear sdram is not required.
@paulb-nl, is it fixed the FIFA 96 glitches also ?

**Comment by paulb-nl** [comment]
I can't get the glitches with Fifa 96 anymore but it happens randomly so I'm not sure it is fixed.

It happens when the Fifa soccer letters scroll from the left with the vertical scrolling bar. Some static sprites will appear on the vertical bar.

**Comment by wwark** [comment]
ok maybe opened a new ticket for this game.
