### ISSUE TITLE
[SGB Mode] Disney’s Hercules has no sound/music

### ISSUE THREAD

**Issue by italiangrandma** [MiSTer-devel/Gameboy_MiSTer#122]
Game functions as it should in standard GB mode. Only has no sound/music when Super Game Boy is On.

**Comment by paulb-nl** [comment]
This game uses the Super Nintendo sound hardware on the Super Game Boy so sound/music won't work on this core. It can only work if Super Game Boy is added to the SNES core.

**Comment by italiangrandma** [comment]
Makes sense!

**Comment by paulb-nl** [comment]
Can be played with music on the Super Gameboy core.
