### ISSUE TITLE
Feature Request:  Gameboy audio interference buzz option.  

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/Gameboy_MiSTer#124]
I know some people are going to roll their eyes at me, but please hear me out.  

The creator of the Sameboy emulator recently implemented this feature that mimics the audio interference you sometimes hear when booting up a GB game. On paper this would seem like a "useless" feature nobody would want, but there is actually demos out there where the developers intentionally abuse this audio interference that is inherent in Gameboys.   Link of the feature in action below, and some words from the dev himself responding to my question.   

Look, I get it, we all have opinions about what features are cool and what seem odd, or pointless, but I think implementing some oddball behavior as an option here and there is not a bad thing for a preservation project, especially if it doesn't break anything.

https://twitter.com/liji32/status/1344067474371846153

![Buzz](https://user-images.githubusercontent.com/36483667/103433139-36771300-4bb1-11eb-8119-1cb1e439ae29.jpg)

Here's a link to a demo that takes advantage of this hardware bug, will be useful for implementation.

https://blog.gg8.se/wordpress/2013/01/13/gameboy-project-week-2-mystery-rom/

**Comment by SegaSnatcher** [comment]
I'll just close this as I feel nobody will bother to do this anyways lol.

**Comment by sorgelig** [comment]
Requests not always implemented immediately. It's also can be implemented by other person who feel he can do it.

**Comment by SegaSnatcher** [comment]
> Requests not always implemented immediately. It's also can be implemented by other person who feel he can do it.

To clarify, I didn't close this out of impatience.  I just wanted to prevent people from making fun of me for putting up a feature request for such odd original behavior that some would consider stupid.

**Comment by SegaSnatcher** [comment]
Ok, I'll reopen this odd feature request since you don't seem to have a problem with it.  Thanks

**Comment by SegaSnatcher** [comment]
There are more important things to worry about than this weird feature request lol.  I would much rather the PCM audio bug was looked into than this, so I'm closing this.
