### ISSUE TITLE
SRAM management

### ISSUE THREAD

**Issue by catskull** [MiSTer-devel/Gameboy_MiSTer#13]
Is it possible to import/export SRAM data?

**Comment by brNX** [comment]
be patient, it's in the pipeline :wink:

**Comment by catskull** [comment]
Awesome, just wasn't sure if it was undocumented or something.

Thanks for your work on this core! Very interested in using this for chipmusic production.

**Comment by brNX** [comment]
@catskull Cool ,
You probably saw kitrinx implemented sram management, should be available in the next release.
If you find sound issues, preferably ones that are easy to replicate ping me

**Comment by catskull** [comment]
When it's released I'll test! Do you know if the implementation is one .sav per rom, or something else? Will I have to manually create blank .sav files?

**Comment by brNX** [comment]
yup , it's one save per rom and no you don't need to create it yourself, it works the same way as the snes core (or other cores without slots).

**Comment by catskull** [comment]
One thing I noticed while testing, it appears the .sav file created by mister is not compatible with .sav files on real hardware or emulators (like BGB). Ideally I'd love to be able to import and export .savs from mister (mostly for LSDJ stuff). Did I do something wrong? I can provide two example .savs as well if that's helpful.

**Comment by brNX** [comment]
No, you didn't. I noticed the same thing but haven't rechecked since, it can be a problem with endianness. Are the BGB saves compatible with real hardware?

**Comment by catskull** [comment]
They are! As far as I know they are fully compatible.

**Comment by brNX** [comment]
ok ,thanks for the info, will try to investigate this when I have the time.

**Comment by brNX** [comment]
it would be easier to maybe write a rom(or preferably find and existing one) to zero the save and then write something to it and then compare , on the real hardware you can have "garbage" or unused space with random values.
