### ISSUE TITLE
Custom palettes are not saving

### ISSUE THREAD

**Issue by iw0rm3r** [MiSTer-devel/Gameboy_MiSTer#132]
If I select any custom palette in Gameboy core setting and choose "save settings" after that, on next core load palette will be reverted to the default one. Core version is Gameboy_20210109.rbf (latest), palette files are in the "Games\Gameboy" directory with subdirectories (strocture is the same as in palettes archive in this repo). If I'm putting palette file to the "Games\Gameboy" directory itself, issue still persists.

**Comment by SegaSnatcher** [comment]
You have to rename the palette to boot0.rom and put it in the root of the Gameboy folder.

**Comment by iw0rm3r** [comment]
Oops... I missed that from the readme. Thank you! Topic can be removed.

**Comment by paulb-nl** [comment]
Fixed in release 20210329. boot0.rom is not needed anymore.

**Comment by sorgelig** [comment]
issue is irrelevant now.
