### ISSUE TITLE
Menu Selection off by One

### ISSUE THREAD

**Issue by dmleet** [MiSTer-devel/Gameboy_MiSTer#133]
I've tried this on the last two releases (20210108, 20210109). The 'GAMEBOY' menu selected options are off by one. For example, If I have 'Super Game Boy' selected and I press A, it changes the 'System' option above it instead of the highlighted option. Other menus work properly, as do the menus for the other cores I've tried.

**Comment by sorgelig** [comment]
make sure you've updated Main to latest.
