### ISSUE TITLE
Flickering picture since the last update

### ISSUE THREAD

**Issue by Milongero71** [MiSTer-devel/Gameboy_MiSTer#137]
Hello,
with the last update of the cores
Atari ST, GameBoy, Coco2 and ZX Spectrum I have now a flicker in the picture and OSD. I used a LCD monitor via the analog output on the I/O board. I have activated the scaler.
I have tested the previous versions and they give a clean picture.

**Comment by sorgelig** [comment]
This will be fixed soon.

**Comment by paulb-nl** [comment]
Can be closed.
