### ISSUE TITLE
Warlocked and Vigilante 8 hang due to IRQ changes

### ISSUE THREAD

**Issue by RobertPeip** [MiSTer-devel/Gameboy_MiSTer#141]
Vigilante 8 hangs when the 2nd intro screen switches to the 3rd.
Warlocked hangs in the intro if not skipped with start button.

It starts failing with this commit
https://github.com/MiSTer-devel/Gameboy_MiSTer/commit/c26731fcabf723c5e4c0e78758b157531d0ef729

The later fix (Commit "Fix IRQ acknowledge edge case") doesn't resolve the problem unfortunatly.

**Comment by paulb-nl** [comment]
The IRQ changes caused an extra HBlank interrupt at the beginning of line 0 after Vblank. 

https://github.com/MiSTer-devel/Gameboy_MiSTer/blob/30b428e52cae71f16c8c126df23bb641ecdb7bf6/rtl/video.v#L259-L261

Tweaking VBlank fixes this. Change above to `if (h_cnt[1:0] == 2'b11) begin` 

It doesn't seem to create regressions with the Mooneye PPU tests. Can you also test it?

**Comment by RobertPeip** [comment]
I can test it later today. Thanks for looking into it so fast!

**Comment by RobertPeip** [comment]
Tested both games and they work again now.
All mooneye PPU tests that passed before, still pass and those failing, fail at the same spot.

**Comment by RobertPeip** [comment]
fixed by Paul
