### ISSUE TITLE
Screen goes black for 1-2 seconds while playing when vsync_adjust=2

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Gameboy_MiSTer#144]
vsync_adjust=1 works nicely but when set to vsync_adjust=2 this core behaves differently from other cores and makes it unusable. The screen goes black sporadically for 1-2 seconds due to HDMI resolution change, I think.

**Comment by wwark** [comment]
Hi @dfilskov,
I think the problem you describe is also in the Readme : https://github.com/MiSTer-devel/Gameboy_MiSTer#video-output

**Comment by dfilskov** [comment]
Oh I see - thanks! - Do you know what the "Stabilize video" option is (which should fix this but introduces latency)? - I don't remember seeing it in the OSD. I did make the black screens go away, though, by using vsync_adjust=1 instead. I guess that introduces latency too - but which of the two solutions introduces less ... hmm. Perhaps Robert Robert Peip knows.

**Comment by paulb-nl** [comment]
Latency:
vsync_adjust 0 & 1 = 2 frames
vsync_adjust 2 = 0 frames
Stabilize video = variable between 0-1 frame.

So the best is vsync_adjust=2 and Stabilize video On.

**Comment by dfilskov** [comment]
Thank you! - appreciated!
