### ISSUE TITLE
Mooneye/Wilbertpol PPU Timing tests fixes

### ISSUE THREAD

**Issue by paulb-nl** [MiSTer-devel/Gameboy_MiSTer#146]
I changed a lot of the PPU timings to fix the PPU timing tests. All Mooneye/Wilbertpol PPU tests now pass except lcdon_write_timing-GS. 

There were also some Halt/Interrupt changes needed for the CPU. The Gameboy Color has a difference compared to the Gameboy of when it exits out of Halt which affects some tests.

Before merging the fixes it would be good to test for regressions so I have attached the rbf here.
[Gameboy_ppu_timing2.rbf.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/6149268/Gameboy_ppu_timing2.rbf.zip)

https://github.com/paulb-nl/Gameboy_MiSTer/tree/ppu_timing

https://github.com/Gekkio/mooneye-gb

https://github.com/wilbertpol/mooneye-gb

Wilbertpol built roms: [wilbertpol.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/6148899/wilbertpol.zip)

**Comment by SegaSnatcher** [comment]
I tested this build for a bit.  The only issue I noticed so far is that some of my save states were corrupted.  Not all, but a few of them.

**Comment by SegaSnatcher** [comment]
I've run a decent amount of games with no issues yet.

**Comment by paulb-nl** [comment]
Thanks for testing @SegaSnatcher

**Comment by wwark** [comment]
Hi @paulb-nl,
Thank you for those improvements !
Same as @SegaSnatcher no issue found on my side.
