### ISSUE TITLE
Feature Request: Super Game Boy border animations

### ISSUE THREAD

**Issue by siskavard** [MiSTer-devel/Gameboy_MiSTer#152]
Most of the borders on the Super Game Boy cartridge will start to animate if left idle for a few minutes, example: [https://youtu.be/6ArYj4-Ajs4?t=60](https://youtu.be/6ArYj4-Ajs4?t=60)

**Comment by Toryalai1** [comment]
Have you tested the super game boy core?

**Comment by maij** [comment]
I think this is a "won't fix" issue. There's a better alternative to putting this into the Gameboy core.

**Comment by siskavard** [comment]
> I think this is a "won't fix" issue. There's a better alternative to putting this into the Gameboy core.

I posted this before the Super Gameboy core existed. 

The only downside to using that core is the lack of save states currently.

**Comment by Toryalai1** [comment]
This ticket can be closed
