### ISSUE TITLE
MBC3 with 64KByte RAM not supported

### ISSUE THREAD

**Issue by RobertPeip** [MiSTer-devel/Gameboy_MiSTer#154]
Some MBC3 carts (probably only pirated ones) support 64Kbyte of RAM.

This mode is possible to define in the header and supported by e.g. Sameboy.
We could also do this by:
- using a 3bit ram_mask in MBC3
- add "cart_ram_size" mode 5 = 64Kbyte, which is currently missing

**Comment by paulb-nl** [comment]
Apparently MBC3 with 64Kbyte RAM is MBC30:
https://gbhwdb.gekkio.fi/cartridges/mbc30.html
https://gekkio.fi/files/gb-docs/gbctr.pdf Page 44

It also supports 4MB ROM (256 banks) so ROM mask/bank also need an additional bit. 

I'll add it to the MBC3 mapper.

**Comment by RobertPeip** [comment]
It seems both combinations are possible. Got a game here (chinese Pokemon) that is 2Mbyte only, but wants 64Kbyte SRAM.
Thanks a lot for looking into it.

**Comment by paulb-nl** [comment]
Added with 08e8724e63d12a0301ab9939f68ef0b8a9ce359b.
