### ISSUE TITLE
[SGB][AUTO] Namco Gallery Vol.3 (Japan) (SGB Enhanced) - Sprite border Issue on the game

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#159]
Hi,

Sorry I don't have a hardware to test sgb mode and use the last version of the core for this test (https://github.com/MiSTer-devel/Gameboy_MiSTer/commit/bc230af7c0ed3a57dedca241140b285412b8e5d0)
You will see the issue on the screenshot below, a sprite border is present on the title screen on the game Jantaku Boy (mahjong)
![20210421_182917-Namco Gallery Vol 3 (Japan) (SGB Enhanced)](https://user-images.githubusercontent.com/469461/115589747-81d43f00-a2d0-11eb-954b-27d3d4d7cc9b.png)

Sha1sum of the rom is a8902e4af858b28c1c934879718e8c971a2000bb

Thanks,

**Comment by paulb-nl** [comment]
Games should only use tile numbers 0-255 for the border but they were naughty and used higher numbers for those two tiles.

#160

**Comment by wwark** [comment]
Thanks @paulb-nl Great fixes as always.
I found another game with tile in the game (fix with this commit)
Also I found two games hangs in SGB mode (working if we set sgb mode to offs) working great with this PR !

**Comment by paulb-nl** [comment]
Which games were hanging? This change should only affect the border. 

Sometimes I get that fast forward is accidentally enabled and causing games to hang on boot.

**Comment by wwark** [comment]
It is hanging just on SGB Mode:
Pocket Kanjirou (Japan) (SGB Enhanced).gb
Soukoban Densetsu - Hikari to Yami no Kuni (Japan) (SGB Enhanced) (GB Compatible).gbc (with mode gameboy)
If I set off the sgb mode the games runs.

**Comment by paulb-nl** [comment]
Oh I see. It looks like those games hang but it's just the border was completely covering the Gameboy screen. That's why those are also fixed now.

However, the border of Soukoban Densetsu is missing. Now it is just completely blue.

**Comment by wwark** [comment]
Yes I saw it !
Some games like "Contra Spirits (Japan) (SGB Enhanced).gb" doesn't have specific boder so use the default one.
I understand now !
