### ISSUE TITLE
[GBC] Voice samples not audible in Sakura Taisen GB

### ISSUE THREAD

**Issue by TheOpponent** [MiSTer-devel/Gameboy_MiSTer#176]
This game has a number of digitized voice samples, none of which are audible in the Game Boy core version 20210508.

This can be reproduced by selecting the default option はじめから (New Game) in the main menu. One of six random voice samples is intended to play, but silence is heard instead in the core. This occurs with and without the official BIOS.

Example on hardware: https://youtu.be/3baIajBuyio?t=138

**Comment by SegaSnatcher** [comment]
Likely related to this issue I opened up about PCM audio.

#143

**Comment by lhathcock** [comment]
Can confirm testing this on hardware vs. core. Interestingly, PCM audio in TMNT II: Back From the Sewers seems to be working fine.

**Comment by maij** [comment]
I have also confirmed this, and I am quite confident that it is has the same cause as #143.

By implementing high-pass filtering (HPF) at the sound output (to emulate the on-board analogue HPF) I can now hear the voice samples from Perfect Dark GBC and Sakura Raisen. Shall we merge these issues, and I can provide more info in the #143?
