### ISSUE TITLE
Release 20210930 breaks Super Mario Land 2

### ISSUE THREAD

**Issue by RobertPeip** [MiSTer-devel/Gameboy_MiSTer#178]
Game is broken with the newest release as soon as you need to select one of 3 pipes, so basically direct from the start.
Last release is still working.

@paulb-nl
Would be great if you could check if this from the mapper changes or from the sys changes.

Thanks,
Robert

**Comment by paulb-nl** [comment]
Thanks Robert, I don't know how I missed this bug....

It is fixed now with #179

**Comment by IndoJimbo** [comment]
When is this update being pushed out? Warioland is  broken to.

**Comment by paulb-nl** [comment]
Fixed with release 1107.
