### ISSUE TITLE
Left and Right audio are switched

### ISSUE THREAD

**Issue by catskull** [MiSTer-devel/Gameboy_MiSTer#18]
I have been doing some A/B comparisons between MiSTer and a DMG. Happy to report it's really good (even fooled some chiptune producers). The only issue is that using the I/O board, left and right audio channels are reversed from the DMG. Not sure if this needs to be fixed in the core or in hardware.

Here's some recordings:
DMG - https://drive.google.com/open?id=11R-NB4dmdAKJjca-1M1-ANlJHEvbJwWv
MiSTer - https://drive.google.com/open?id=1NIJGMaJxmMwcy1Ih5HfZWV78CT5OIDvJ

**Comment by brNX** [comment]
was fixed in #17 2dc618f3f82740f7ce94c042ac47f023323e5d61, the sound registers where swapped

**Comment by catskull** [comment]
Ah, saw the PR but didn't see a note. Closing!
