### ISSUE TITLE
[GBC] Pocket Puyo Puyo Sun Graphics Glitch

### ISSUE THREAD

**Issue by CharlesLove** [MiSTer-devel/Gameboy_MiSTer#181]
### Issue
When getting matching 4 or more puyo, a graphics corruption slides in instead of the player or opponent sprite.
### How to replicate
1. Keep pressing A until you get in a match.
2. Match 4 or more same colored puyo and make a match.
3. The skeleton will disappear and graphics corruption will be in its place. The intended behavior is your character should slide in and strike a pose.
### Note
This issue does not occur with Pocket Puyo Puyo-n (the sequel) or when Sun is run in an emulator, so I don't believe it's a bad dump. Probably a chip that isn't mapped.

**Comment by paulb-nl** [comment]
Fixed with release 1107.
