### ISSUE TITLE
Aladdin GBC Version

### ISSUE THREAD

**Issue by IndoJimbo** [MiSTer-devel/Gameboy_MiSTer#186]
Aladdin crashes after splash screen.

Build 1107

**Comment by paulb-nl** [comment]
This game starts a WRAM -> OAM DMA while executing from ROM. This is only possible on GBC because it has a separate WRAM and Cartridge bus.

Fixed in release 1121 by 2797679a0fb8f0bc665675bfabc7dc4cd9c6b5dd
