### ISSUE TITLE
Possibility of hardware link port

### ISSUE THREAD

**Issue by catskull** [MiSTer-devel/Gameboy_MiSTer#19]
What is the possibility of adding support for a link port? I understand it would require a special I/O pcb, but many would probably be interested in having this available. Luckily Gameboy link ports are still being made. If support is added I can design a custom I/O board that has the hardware needed.

**Comment by brNX** [comment]
It should be possible, I think there are some pins available on the arduino header that don't conflict with existing MiSTer addon-boards, but sorry, for now at least it's not in my priority list. But hey it's open source, maybe someone else.

**Comment by catskull** [comment]
Very understandable! I appreciate all your hard work on this.

If you're interested, I'd love to put a bounty on this feature!

**Comment by Chocobobobo** [comment]
Wish granted!

https://www.youtube.com/watch?v=fZin_BHa7Ew

**Comment by sorgelig** [comment]
already implemented
