### ISSUE TITLE
How would you like us to go about submitting color palettes?

### ISSUE THREAD

**Issue by Numbski** [MiSTer-devel/Gameboy_MiSTer#204]
I have a couple here that I can't claim credit for, I merely converted them with use by the Gameboy core.  Seems silly for me to clone your whole repo to add a couple of tiny files and then do a pull request, but if that's how you'd like to see them, then I don't mind.

**Comment by Numbski** [comment]
Hah, well - I was going to attach them to this issue, but I keep getting errors whether I use tar.gz or zip.  Really bizarre behavior.

**Comment by thehughhefner** [comment]
I have created a pull request with those pallets that you have attached. See here: https://github.com/MiSTer-devel/Gameboy_MiSTer/pull/208

**Comment by Numbski** [comment]
Thanks, that is awesome.  Hopefully others like them.

Tony Shadwick
