### ISSUE TITLE
Autoload boot2.rom is no longer working

### ISSUE THREAD

**Issue by uberyoji** [MiSTer-devel/Gameboy_MiSTer#205]
I tried several roms and as soon as I put boot2.rom the boot sequence stays on a white screen.
It used to work previously.

Doing a reset will sometimes make it go thru.
 
Tried also several settings like fast boot to see if there is some pattern but could not find something solid.

**Comment by uberyoji** [comment]
I think it stopped working when megaduck support was added. I see if I force Gameboy in System it is working again. Maybe because in Auto modr it can figure out what boot2.rom's system is and won't load.

**Comment by paulb-nl** [comment]
It should work again with release 0806 and Gameboy Color roms now also work as boot rom with System set to Auto.
