### ISSUE TITLE
[GBC] Donkey Kong 5: The Journey of Over Time and Space (Unl, Bootleg) - Freezes on Game Boy logo

### ISSUE THREAD

**Issue by italiangrandma** [MiSTer-devel/Gameboy_MiSTer#209]
Using the (fixed) version of the rom, it hangs on the Game Boy logo.

**Comment by paulb-nl** [comment]
The header checksum is incorrect so the GBC boot rom will not boot the game. Change value at address $014D from $02 to $01 and it should work.

**Comment by italiangrandma** [comment]
@paulb-nl Yeah, someone on Discord actually clued me in to this! I grabbed the "fixed" version of the rom, ran it through Game Boy Rom Analyzer using the fix header function and it works now!
