### ISSUE TITLE
Fastboot option removed?  

### ISSUE THREAD

**Issue by Zelink1** [MiSTer-devel/Gameboy_MiSTer#213]
This core use to have a fast boot option for the bios, but I can no longer find this option in the Gameboy menu.

**Comment by sorgelig** [comment]
it's in Misc sub-menu

**Comment by Zelink1** [comment]
> it's in Misc sub-menu

Yes, in the old releases, but the current release it is not in misc.

**Comment by Zelink1** [comment]
Here is the option in the 02/14/22 release of the core.

![DSC00319](https://user-images.githubusercontent.com/105920087/185064975-57d87e48-9022-4546-8b07-44e4a50bdf5c.JPG)

**Comment by Zelink1** [comment]
Looks like this feature was removed maybe accidently in this commit.  

https://github.com/MiSTer-devel/Gameboy_MiSTer/commit/c9e40b3514e94df218c432650f619c3aa27014b5

**Comment by sorgelig** [comment]
may be @paulb-nl will comment it

**Comment by paulb-nl** [comment]
The Fast boot option was just switching to a different boot rom when enabled. Now that you can load custom boot roms the option is no longer needed. 

`dmg_boot.bin` in the BootROMs folder is one with a fast boot so load that with `Load DMG boot *.bin`
https://github.com/MiSTer-devel/Gameboy_MiSTer/tree/master/BootROMs

**Comment by Zelink1** [comment]
> The Fast boot option was just switching to a different boot rom when enabled. Now that you can load custom boot roms the option is no longer needed.
> 
> `dmg_boot.bin` in the BootROMs folder is one with a fast boot so load that with `Load DMG boot *.bin` https://github.com/MiSTer-devel/Gameboy_MiSTer/tree/master/BootROMs

OK, thanks.
