### ISSUE TITLE
Gameboy core only shows a corrputed screen with an ® and I can't open the menu

### ISSUE THREAD

**Issue by c-a0** [MiSTer-devel/Gameboy_MiSTer#215]
When I start the Gameboy core, all I see is a white screen with some random black pixels and the ® symbol. I can't open the menu with the osd button on the MiSTer. The only button that responds is the reset button. If I mash the buttons on my controller, sometimes the corruption on the screen changes and then the screen turns completely white.

**Comment by maij** [comment]
I cannot reproduce this. Can you confirm which version of the core you are using?

**Comment by paulb-nl** [comment]
Can't reproduce.
