### ISSUE TITLE
Feature Request: Rom for Second GB

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Gameboy_MiSTer#220]
Just a feature request to add the "Rom for second GBA" option to the Game Boy core as it works in the GBA core. Since it's primarily used to trade and battle Pokemon games in the GBA core, the same functionality could hopefully happen on the Game Boy core with the Gen 1 and 2 Pokemon games. I think the Yu-Gi-Oh games use this functionality too :)

**Comment by paulb-nl** [comment]
Added with release 20240918
