### ISSUE TITLE
Boarder Zone: Crazy color glitches

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Gameboy_MiSTer#223]
When playing Boarder Zone, the colors glitch out like crazy when starting a race of any kind. If you pause and unpause the game, it fixes itself for a few seconds before turning the snow mountain from its normal colors into some crazy rainbow sherbert colors lol

**Comment by paulb-nl** [comment]
Fixed by 11750b0230b5babcf485f6c6b50950621f410fe4

Caused by HDMA pausing the CPU during a write to BGPD which resulted in BGPI incrementing every cycle.
