### ISSUE TITLE
Tarzan (GBC) constant grating buzzing noise

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Gameboy_MiSTer#224]
When playing Tarzan on GBC there's a constant grating buzzing noise that starts w/ the intro cutscene and persists throughout the whole game. The only time it stops is when you pause the game.

**Comment by paulb-nl** [comment]
Fixed by a6f94d64636a4614c7e7b0b35db522b06fbbeb1b
