### ISSUE TITLE
GameboyColor.mgl is lacking spaces in the name

### ISSUE THREAD

**Issue by one-piece19** [MiSTer-devel/Gameboy_MiSTer#228]
Well, the GameboyColor.mgl is lacking spaces in the name, it should be "Game Boy Color.mgl" to match the names of the other cores and mgl files

**Comment by Toryalai1** [comment]
There was a ticket about this already where they renamed it from Game Boy Color.mgl to GameBoyColor.mgl: https://github.com/MiSTer-devel/Gameboy_MiSTer/pull/226

**Comment by Toryalai1** [comment]
You can use the names.txt file to rename GameboyColor.mgl to whatever you like. Sorg added functionality to rename mgl files. This ticket can be closed
