### ISSUE TITLE
Donkey Kong Land:  Corrupted player sprite after having encountered sprite flickering (many enemies on same line)

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/Gameboy_MiSTer#242]
Hello,

In Donkey Kong Land, the player sprite appears corrupted in motion after playing a while. It seems to trigger after you have sprite flickering due to being many enemies on the same line:

https://youtu.be/Q7baFhHCruQ

![image](https://user-images.githubusercontent.com/86253908/235753382-11a47ba3-8aa2-43ea-84e2-147f65b7d160.png)

I was playing in Game Boy Color mode.

**Comment by maij** [comment]
Have you tried the stabilize video option in the Audio and Video menu?

**Comment by paulb-nl** [comment]
That is what happens on real hardware on Gameboy Color with the Donkey Kong Land games. 

Check out this video at 2:50: https://youtu.be/4wLuwm39S3Y?t=170

**Comment by AtomicShroom** [comment]
> That is what happens on real hardware on Gameboy Color with the Donkey Kong Land games.
> 
> Check out this video at 2:50: https://youtu.be/4wLuwm39S3Y?t=170

Oh snap! Didn’t think in a thousand years this would have happened on real hardware. Let’s close it then!
