### ISSUE TITLE
[GBC] Issue to play GBVideoPlayer2

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#245]
Hi,

The core doesn't behave correctly for running roms generated with GBVideoPlayer2.

Readme explaining working on real hardware;
https://github.com/LIJI32/GBVideoPlayer2/blob/master/README.md

Some test roms here : https://github.com/LIJI32/GBVideoPlayer2/releases

Screenshot of butterfly.gbc:
![20240105_010143-butterfly](https://github.com/MiSTer-devel/Gameboy_MiSTer/assets/469461/fe42a548-177d-463a-ac68-9a58b391aea4)

Thanks,

**Comment by paulb-nl** [comment]
The roms size are not padded to a power of 2. The core doesn't support that yet. 

It will work if you pad them to the correct size.

**Comment by paulb-nl** [comment]
You can leave the issue open to remind me to fix this.

**Comment by wwark** [comment]
Thanks a lot :+1:  I will test to change the padding of the Rom and leave the issue opened for a fix.

**Comment by wwark** [comment]
@Toryalai1 The issue is still present with butterfly.gbc (not pactched with the padding change)

**Comment by wwark** [comment]
Sorry I respond to quickly I didn't check with the last unstable it is working now :+1: 
thank you @Toryalai1 for the ping and thank you @paulb-nl for the fix.

the ticket is closed
