### ISSUE TITLE
Mega Duck Rumble Not Working

### ISSUE THREAD

**Issue by bebopjp** [MiSTer-devel/Gameboy_MiSTer#247]
Did a check at the Mister menu to confirm my controller's rumble is working properly using L+X and L+Y.

Tested with the PSX core and rumble worked.

Tested with Pokemon Pinball on the GBC with this core and rumble worked.

I can't seem to get any Mega Duck game to work with rumble.  I'm not sure if I'm missing something setting up the Mega Duck.

**Comment by paulb-nl** [comment]
There are Mega Duck games with rumble?

**Comment by bebopjp** [comment]
Hmmm, actually, I don't really know since I don't have actual hardware to confirm with.  I'm just assuming from messing with the same games in the SameDuck libretro emulator: https://docs.libretro.com/library/sameduck/

The game I used to test was Black Forest Tale.

**Comment by paulb-nl** [comment]
The SameDuck emulator generates Rumble from the sound. Mega duck games don't have native support for Rumble.
