### ISSUE TITLE
Feature Request: Support for Mobile Adapter GB

### ISSUE THREAD

**Issue by Casuallynoted** [MiSTer-devel/Gameboy_MiSTer#249]
Hello!

While SNAC link support currently works for linking to consoles, it doesn't currently work when the link port is connected to the GB mobile adapter or a replica GB mobile adapter made using a Rpi Pico (both of these devices are functionally the same). Mobile GB games have been revived and translated thanks to the REON project, seen here:
https://github.com/REONTeam/libmobile

And currently I can use my mobile GB adapter with both a Gameboy Player and actual Gameboy hardware, but not a MiSTer FPGA. I'd like to see if perhaps support for this awesome accessory can be added to the core.

**Comment by kconger** [comment]
I just built a https://github.com/zenaro147/PicoAdapterGB and I'm able to use it with MiSTer.

**Comment by Casuallynoted** [comment]
> I just built a https://github.com/zenaro147/PicoAdapterGB and I'm able to use it with MiSTer.  

Hmm, that's the exact kind I'm using. What settings/options did you enable in the core to use it? Maybe I'm missing something.

**Comment by kconger** [comment]
I've have the core system set as Gameboy Color, GBC/GBA mode set to GBC and have Link Port enabled.

Mobile Trainer is able to detect the adapter and attempt to connect to the server after account setup. I don't have a server yet to test any further unfortunately.

**Comment by Casuallynoted** [comment]
Weird, that's the exact settings I'm using. I'll give it another try and report back.

**Comment by paulb-nl** [comment]
I will close this issue since it seems to be working.
