### ISSUE TITLE
High notes in music have lowered pitch

### ISSUE THREAD

**Issue by Weario** [MiSTer-devel/Gameboy_MiSTer#252]
I've noticed this when I recently updated the cores in mister (including the latest gb update).

I was playing some Wario Land 3 and noticed the background music in 'The Vast Plains' at nighttime sounded different.
Not everyone may be able to hear this very high tone, but here's the actual soundtrack: https://www.youtube.com/watch?v=mm89yzN2n-E
That very high note - for some reason - has it's pitch lowered since the latest core update.

If I find a way to record the music from my AVR, I'll post the recording of that as well.

**Comment by paulb-nl** [comment]
You have very good ears. The pitch of that tone was lowered by 20%.

It is fixed here 7c576b02e88306e97a7c7757ea99994099f88cb0

**Comment by Weario** [comment]
Thank you for the fix, I really appreciate it!

**Comment by Weario** [comment]
Sorry to bother again, but is the fix going to be released anytime soon? Looks like the latest release was 5 months ago.

**Comment by sorgelig** [comment]
i will release soon

**Comment by Weario** [comment]
Thanks so much!

**Comment by paulb-nl** [comment]
Fix released with 20240912
