### ISSUE TITLE
Loud pop at the beginning and end of sounds

### ISSUE THREAD

**Issue by BreakPoints** [MiSTer-devel/Gameboy_MiSTer#256]
Discovered using the Analogue Pocket port ([reported here](https://github.com/budude2/openfpga-GBC/issues/60)) there is a loud pop at both the beginning and end of playing a sound. This wasn't present in earlier builds, possibly before #250.

If this is intended, hardware correct behaviour I would like to request a way to optionally mitigate the pop artifact as it is rather unpleasant to play with.

**Comment by sorgelig** [comment]
You need to contact Analog pocket port developers. This is MiSTer repository.

**Comment by BreakPoints** [comment]
> You need to contact Analog pocket port developers. This is MiSTer repository.

The linked report in my first post is from the Analog Pocket repository where the sole developer suggested it could be an upstream issue. I don't have a MiSTer so I was hoping someone here would be able to confirm for me.
