### ISSUE TITLE
Sleep and wake forgets the SGB BIOS and continues the game with GB BIOS

### ISSUE THREAD

**Issue by Hyourinmaru0** [MiSTer-devel/Gameboy_MiSTer#258]
I use the Analogue Pocket with the GameBoy Core from budude2, which is a port from this core. I don't know if the bug also occurs in this form with MiSTer.

When I sleep the Analogue Pocket with a running rom, that supports the SGB enhanced colors, e.g. Pokémon Red/Blue/Yellow, which was loaded with the SGB BIOS, and wake the console and resume the game, it forgets the game was loaded with SGB BIOS and it seems the game continues with GB BIOS without the SGB enhances. It shows the color palette from Gameboy Color/Advance and the SGB color enhances does not work, until the SGB BIOS ist manually loaded again or the core ist reset or exited and started again. However the 'Enable SGB' option is still checked.
I have attached a video file from the curious behavior recorded with my smartphone.
https://github.com/user-attachments/assets/821cbf43-761d-4f27-817c-2223f696b673

**Comment by sorgelig** [comment]
it has nothing to do with MiSTer.
You have to contact manufacturer of your device.

**Comment by paulb-nl** [comment]
This core does not save the SGB data in the save state so save state loading does not work properly with SGB enhancements.

**Comment by sorgelig** [comment]
Besides that MiSTer has no sleep state.
