### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by brNX** [MiSTer-devel/Gameboy_MiSTer#28]
This is a list of issues that I am aware off:

- [ ] PPU Timing issues ("Super Hunchback" blinking lines, prehistorik man ,~~street fighter 2 blinking background~~...)
- [x] GBC Hicolour mode (probably related to ppu timings)
- [x] Donkey Kong Country GBC freezing
- [x] Mega Man extreme GBC unplayable (no ground , mega man falls to death)
- [x] Missing Sprites (~~Prehistorik man~~, super mario 2 dx , ~~xenon 2~~)
- [ ] Wave channel has noise in some GBC games/demos (e.g.: Bad Apple)
- [ ] General sound crackling in some games (Final Fantasy Legend III and Gargoyle's Quest intros)
- [x] Test Drive 6, 2001 and Offroad don't show the initial intro and menu but go in-game (by pressing A blindly)
- [x] Test Drive le mans crashes after the language selection
- [x] Konami GB Collection  Vol.4 (GBC) white screen in intro and graphical issues 
- [x] Konami GB Collection  Vol.2 (GBC) white screen in intro and freezes
- [x] ~~Input not working in Shantae's dance minigame  , freezes at the end~~ (Input is working , freeze at the end if 0 gems won is original game bug [https://www.romhacking.net/hacks/3785/](https://www.romhacking.net/hacks/3785/) )

**Comment by catskull** [comment]
If it's helpful, this rom demonstrates noise in wave channel/sample playback pretty well.
[sndtest.gb.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/2853194/sndtest.gb.zip)

**Comment by brNX** [comment]
thank you @catskull that should help a lot, not having to deal with code that isn't related to audio helps a ton.

**Comment by brNX** [comment]
I'll close this one and open individual issues for the remaining bugs,
Super hunchback is interrupt related.
The sound issues are probably a mix from the same issue and need of the correct filters. (The bad apple issue is present on an original GBA but not on a GBC)
