### ISSUE TITLE
Castlevania - The Adventure (USA) - Time Left Problem

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/Gameboy_MiSTer#40]
per our discussion brNX, here is the issue.  So, the time that displays at the top of the screen, centered, has some glitchiness.  Some of the digits will disappear, reappear, then go away entirely.  Attached are some screenshots, from Alan's new utility.

![20190514_083510-Castlevania - The Adventure (USA)](https://user-images.githubusercontent.com/47957258/57711781-43ce3b00-7624-11e9-871e-95c800b5191e.png)
![20190514_083512-Castlevania - The Adventure (USA)](https://user-images.githubusercontent.com/47957258/57711782-43ce3b00-7624-11e9-8e02-1f69a6aa799f.png)
![20190514_083515-Castlevania - The Adventure (USA)](https://user-images.githubusercontent.com/47957258/57711783-43ce3b00-7624-11e9-9f19-d3d336cc0708.png)
![20190514_083516-Castlevania - The Adventure (USA)](https://user-images.githubusercontent.com/47957258/57711784-4466d180-7624-11e9-89e8-319e29f41182.png)
![20190514_083607-Castlevania - The Adventure (USA)](https://user-images.githubusercontent.com/47957258/57711786-4466d180-7624-11e9-9c90-649e0987502f.png)

**Comment by brNX** [comment]
thanks for reporting this issue

**Comment by mario-64** [comment]
Any progress on getting this fixed? It’s almost a year old now. Just got my MISTer and am seeing it as well.

**Comment by Hewhoisred** [comment]
As far as I know, there's no active GB dev right now, so we just need to wait.

**Comment by mario-64** [comment]
Oh wow. How disappointing. Thank you for the info

**Comment by Chocobobobo** [comment]
Disappointing? Everything is free and open source... Feel free to offer a bounty or fix it yourself... People are so entitled, this is insane.

**Comment by commonbreed** [comment]
@Chocobobobo Feeling disappointed is a pretty natural reaction to hearing that your issue will likely not be fixed for some time. Doesn't mean their entitled at all. Let's try to be kind online.

**Comment by SegaSnatcher** [comment]
Recent fixes seem to make the displays a bit more stable, but they still flicker from time to time.

**Comment by brNX** [comment]
some flickering, "ghost sprites" and candles that wiggle a little are visible on original hardware (GBC and GBA at least)

**Comment by SegaSnatcher** [comment]
> some flickering, "ghost sprites" and candles that wiggle a little are visible on original hardware (GBC and GBA at least)

I see, That's good to know.    Though I wonder if a theoretical extra sprites feature would help at all with this game.

**Comment by Hewhoisred** [comment]
This game just seems to be flickery/glitchy.  I also confirmed this using Sameboy.  Closing this issue.  Thanks Paul, very excellent work on the core.
