### ISSUE TITLE
Custom color palette selection not saved and/or reloaded

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Gameboy_MiSTer#47]
I prefer the GrafxGreen color palette, so after loading it, I chose “Save settings”, expecting it would stick.  But the next time I loaded the core and launched a non-color Gameboy game, it did not automatically restore the GrafxGreen palette.  I have to go load it manually every time I boot the core.

**Comment by sorgelig** [comment]
if you want to load some palette at boot, rename it to boot0.rom

**Comment by brNX** [comment]
It's in the readme (https://github.com/MiSTer-devel/Gameboy_MiSTer/blob/master/ReadMe.md#autoload)
