### ISSUE TITLE
Super Mario Land (W) v1.1: second row of pixels (in status area) flashes while scrolling

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Gameboy_MiSTer#49]
Second row of pixels on the screen, in the status area, flickers randomly during horizontal scrolling.

**Comment by brNX** [comment]
this one seem to be fixed , the first line shows glitches but those are also present on original hardware.

this can be closed

**Comment by c0d3h4x0r** [comment]
I don’t recall those glitches being present on original hardware.  Did the poor response time of the LCD just hide it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by c0d3h4x0r** [comment]
I see it happens *a little* on original hardware: https://youtu.be/PGLmpjWTTnI

But it’s nowhere near as bad or frequent as it still is on the latest release of the MiSTer core.

**Comment by brNX** [comment]
> I see it happens _a little_ on original hardware: https://youtu.be/PGLmpjWTTnI
> 
> But it’s nowhere near as bad or frequent as it still is on the latest release of the MiSTer core.

with this version 
[Gameboy_20200627.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/4845021/Gameboy_20200627.zip), it looks pretty similar to my gameboy color with the mcwill screen and this recording of the super gameboy 
https://www.youtube.com/watch?v=ns0qFFrtVxM , you can clearly see the same issue especially on level 1-3. 

But sure , leave this open.

**Comment by sorgelig** [comment]
visibility of glitch may also depend on display itself. Original LCD might not show very quick changes.

**Comment by brNX** [comment]
> visibility of glitch may also depend on display itself. Original LCD might not show very quick changes.

yes, the DMG screen is actually very slow, some games even took advantage of it , see issue #85 , those used it to implement more information drawn on screen or "transparency" effects

**Comment by SegaSnatcher** [comment]
Seems to be less flashing in newest release, I could be wrong though.

**Comment by c0d3h4x0r** [comment]
Thanks everyone.  I’ll try it again, and if I still see an obvious difference from the Super GameBoy video, I’ll record a video of what I’m seeing.

**Comment by c0d3h4x0r** [comment]
Here’s a video of what I’m seeing:

https://1drv.ms/v/s!AjhPgJi61wHDtugWoGB8SGmoCsjgzA

It seems to be a little worse, but that could just be due to how I play the game (almost always running).  I would be okay with closing this issue if you think it’s normal.

**Comment by brNX** [comment]
> Here’s a video of what I’m seeing:
> 
> https://1drv.ms/v/s!AjhPgJi61wHDtugWoGB8SGmoCsjgzA
> 
> It seems to be a little worse, but that could just be due to how I play the game (almost always running). I would be okay with closing this issue if you think it’s normal.

Here a video I recorded on my GBC (modded with a McWill backlit screen) https://www.dropbox.com/s/kagbvzqxtsuqta8/supermariogbc.mp4?dl=0

**Comment by sorgelig** [comment]
that's already clear it's original game behavior.
Not an issue.

**Comment by c0d3h4x0r** [comment]
Yep, go ahead and close.
