### ISSUE TITLE
Spot: title music and sound effects aren’t right

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Gameboy_MiSTer#51]
Both the title music and the gameplay sound effects contain high-pitched noises and distortion that are not correct.

**Comment by brNX** [comment]
Is that "Spot (U) [!].gb" ? 

The game relies on a randomized wave table (Channel 3) on reset (just like R-Type and Aladdin), I'll soon send a PR with it fixed. You have to play it in Gameboy mode , in Gameboy color mode it still sounds off (but that's expected)
