### ISSUE TITLE
Resident Evil Gaiden: Missing text

### ISSUE THREAD

**Issue by Zembarian** [MiSTer-devel/Gameboy_MiSTer#54]
After you start a new game, most if not all the text is missing. 

Core used: Gameboy_20190711.rbf

Steps to reproduce: 
1. Start a new game from the title screen and watch the intro.

ROM used is the US release of Resident Evil Gaiden, CRC32 f8c5021b

![NODATE-Resident Evil Gaiden (USA)_0001](https://user-images.githubusercontent.com/52972902/61314259-9088ea80-a7fc-11e9-81ea-d839a2f09dd0.png)
![NODATE-Resident Evil Gaiden (USA)_0002](https://user-images.githubusercontent.com/52972902/61314262-92eb4480-a7fc-11e9-9000-732ae8967f5c.png)
![NODATE-Resident Evil Gaiden (USA)_0003](https://user-images.githubusercontent.com/52972902/61314266-954d9e80-a7fc-11e9-8b70-be43d1e05e1c.png)

compare to https://www.youtube.com/watch?v=CMjDDVkNBW0

**Comment by Ashenshards** [comment]
I'm not sure who fixed this, but latest release has text in this game. Someone should close this ?

**Comment by sorgelig** [comment]
yep, fixed.
