### ISSUE TITLE
Better video configuration for TVs

### ISSUE THREAD

**Issue by nilp0inter** [MiSTer-devel/Gameboy_MiSTer#55]
Hi,

I've been tinkering with the video configuration for TVs on the README and I improved it (at least on my TV :)

With the current configuration the image is in a small square in the middle of the screen, to achieve full screen I set `vscale_mode=0`, the problem was the image now is too big for the screen. I changed the `video_mode` slightly to solve that.

This is the final configuration:

```
[Gameboy]
video_mode=320,8,32,24,215,14,3,31,6048
vga_scaler=1
vsync_adjust=2
vscale_mode=0
```

Hope this helps!

**Comment by brNX** [comment]
I'm closing this one as it shouldn't be needed anymore, thanks.
