### ISSUE TITLE
Dragon Slayer won't run

### ISSUE THREAD

**Issue by Noedell** [MiSTer-devel/Gameboy_MiSTer#56]
Dragon Slayer (http://www.hardcoregaming101.net/dragon-slayer/) boots up fine but after the Nintendo logo, I get a blank screen and no sound.
Anyone know about this one?

**Comment by brNX** [comment]
This seems to have been fixed in the latest version. (Dragon Slayer I (Japan).gb)

**Comment by sorgelig** [comment]
works
