### ISSUE TITLE
Harry Potter and the Chamber of Secrets - Missing sprites and text.

### ISSUE THREAD

**Issue by rikard-softgear** [MiSTer-devel/Gameboy_MiSTer#58]
Start a new game and you will see a Harry with a transparent body and missing legs... also, the text is cut off.

![4ZcXQD6](https://user-images.githubusercontent.com/36540711/65363751-e9666c00-dc0d-11e9-8a16-73f7e584103c.jpg)

**Comment by SegaSnatcher** [comment]
Fixed in recent release.

**Comment by sorgelig** [comment]
fixed
