### ISSUE TITLE
Most right column of pixels is shown on the most left side

### ISSUE THREAD

**Issue by kurtjmeyoung** [MiSTer-devel/Gameboy_MiSTer#59]
Gameboy_20190928.rbf

In all games I tested (via HDMI), the last column of pixels (most right) is shown on the left side of the "screen" (most left pixels). I think this misplaced pixel column is also shifted down a bit (1-2 rows). If you're already aware of this bug, feel free to delete this issue :-)
If you need to have more info, I will gladly assist and do what I can to help.

**Comment by sorgelig** [comment]
Does it present in previous release?

**Comment by kurtjmeyoung** [comment]
I don't think so, no. But if it helps, I can try an older release if you want?

**Comment by sorgelig** [comment]
i will look

**Comment by sorgelig** [comment]
should be fixed

**Comment by kurtjmeyoung** [comment]
Yes, it's fixed. Thank you!
