### ISSUE TITLE
No sound in Elgato hd 60s+ capture card, or via capture card passthru

### ISSUE THREAD

**Issue by GeorgeDemosthenesIII** [MiSTer-devel/Gameboy_MiSTer#60]
I do get normal audio from the Gameboy core on my Samsung tv using hdmi, but get no audio when using elgato capture card or the capture card's hdmi passthru.

**Comment by brNX** [comment]
Can you check this out now with the latest version, that one improved audio tremendously on my TV.

**Comment by sorgelig** [comment]
i don't remember what is exact problem with elgato. If it's because of zero point offset, then it should be fixed in new framework incorporated in latest release. If it's because audio is too quiet, then nothing can be done here except to use max volume in MiSTer and load some game with loud sound.

**Comment by brNX** [comment]
got the confirmation from someone using an elgato hd6 60s+ that everything is working fine, will close this one
