### ISSUE TITLE
Load / save not working?

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Gameboy_MiSTer#61]
I will post this in the MiST version too.

I've composed a bunch of tunes for Gameboy almost 20 years ago - but it doens't work when I load them into SRAM for the Carillon Editor (copying it to the sdcard in saves/gameboy/carillon.sav ). The data doesn't seem to get loaded.

I've attached the .gb for Carillon Editor - and .bin and .sav files for one of my tunes for testing.

[gameboy-save-load-issue.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/3911086/gameboy-save-load-issue.zip)

The Carillon Editor author Alexi Eeben wrote about this issue:
"maybe it’s ”emulating” a wrong memory controller? The old flash carts were (if I recall correctly) of type MBC5"

In Carillon Editor ...
Load tune = click Start button on LOAD FROM SRAM
Play = click Start twice on BLOCK ORDER LIST
Save tune = click Start on STORE IN SRAM

Any ideas how to make it work?

**Comment by catskull** [comment]
The save file and the rom need to be named the same I think. In your zip file the rom is named `carillon.gb` but the save is named `Hiscore v1.1.sav`. Try changing the save to `carillon.sav`? Also I'm not sure what the .bin file is for.

**Comment by dfilskov** [comment]
Thanks! - I figured that too - tried it but no luck.

First I saved to RAM in the music editor, then saved SRAM in the MiSTer menu to know where exactly and what the filename was. Didn't work.

The sav files even had the same sizes.

**Comment by dfilskov** [comment]
Wait ... - it works!! :) - the SRAM file wasn't loaded unless I booted the ROM file. My mistake!

**Comment by catskull** [comment]
Awesome! Hope to see something cool that you're up to!
