### ISSUE TITLE
Loss of sync on HDMI output

### ISSUE THREAD

**Issue by WonkerChonker** [MiSTer-devel/Gameboy_MiSTer#67]
Hi,

Saw the latest patch enabled 15khz output and I was super excited to try it. While dual outputting to a CRT and my crappy flatscreen, I noticed that black screens/blank screens cause a temporary interruption of sync on the HDMI output only. I rebooted the MiSTer with only the HDMI out and saw the issue again. It is pretty easy to reproduce. If you boot up GB tetris and start a game, the screen goes black until the first piece (at speed 0) is halfway down the screen. If you boot up Pokemon Yellow, you'll notice the intro cinematic and any time you enter a battle will cause a loss of sync as well. Forgive me if this is a known issue with the latest patch.

**Comment by PhantombrainM** [comment]
Wiki says:

Video output

The Gameboy can disable video output at any time which causes problems with vsync_adjust=2 or analog video during screen transitions. Enable the Stabilize video option to fix this at the cost of some latency.

**Comment by WonkerChonker** [comment]
How embarrassing. I'll try to do a better job reading the documentation in the future. Thanks.

**Comment by brNX** [comment]
this one can be closed
