### ISSUE TITLE
Pokemon crystal-dialogue text breaks map textures

### ISSUE THREAD

**Issue by WonkerChonker** [MiSTer-devel/Gameboy_MiSTer#68]
Hi,

I notice that if you play through enough of pokemon crystal to obtain your first 'mon, you'll notice a blanking out of vertical strips of the screen. If you talk to someone outside, it'll paint over a strip as the beige/white background color. If you talk to someone indoors, it'll paint a black strip. The miscolored column will persist until you walk it off the screen and walk it back on. 

Thanks

**Comment by brNX** [comment]
This one probably got fixed in the latest release can you confirm ?

**Comment by WonkerChonker** [comment]
Confirmed. It's fixed.

**Comment by brNX** [comment]
> Confirmed. It's fixed.

thanks , this can be closed
