### ISSUE TITLE
Distorted graphics using extended palette

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Gameboy_MiSTer#71]
Extended color palette doesn't work.

Here are comparisons with two games: **Black Diamond Fever** and **Evil Mirror**

![Black Diamond Fever bug](https://user-images.githubusercontent.com/15096058/78676569-e780a380-78e6-11ea-9265-bf3c8f5a3642.png)

![Evi Mirror bug](https://user-images.githubusercontent.com/15096058/78676558-e3548600-78e6-11ea-845c-2859eceed553.png)

**Comment by SegaSnatcher** [comment]
Seems like recent update fixed this issue.

**Comment by sorgelig** [comment]
fixed
