### ISSUE TITLE
Faulty defined buttons on Trip World GB Japan release. 

### ISSUE THREAD

**Issue by babayaga40** [MiSTer-devel/Gameboy_MiSTer#72]
Seems that the defined keys on trip world GB japan only release, seems to change from time to time, sometimes its correct, sometimes A and B switches places, and then goes back again.

**Comment by brNX** [comment]
Hi is this still happening ? I played through the first world and half or so of the second without issues.

**Comment by brNX** [comment]
I'll close this one, I could not replicate it. Feel free to comment if you're still having issues
