### ISSUE TITLE
SolarStriker: Level completion screen not displaying properly

### ISSUE THREAD

**Issue by italiangrandma** [MiSTer-devel/Gameboy_MiSTer#73]
Using v200331

After you complete a level, “Next Stage” is supposed to display with black text over a white background with your ship in the bottom left corner. Instead, the screen goes black with no text displaying, though, your ship is still correctly shown in the bottom left corner.

**Comment by henryrizzi** [comment]
In this most recent release this should be fixed! black text on a white background with the ship in the bottom left corner.

**Comment by sorgelig** [comment]
fixed
