### ISSUE TITLE
Release 20200510 breaks scaling in general and controls in Alleyway

### ISSUE THREAD

**Issue by ThreepwoodLeBrush** [MiSTer-devel/Gameboy_MiSTer#74]
Compared to release 20200331 version 20200510 outputs a much smaller screen and controls in Alleyway do no longer work. It looks like A, Start and D-Pad left are being constantly pressed, starting the game without user input and locking the paddle on the left side.

Different vscale, vsync and video-modes seems to make no difference in this behavior. 

After the core was loaded, the Gameboy-Logo is missing.

**Comment by sorgelig** [comment]
smaller screen is because you enabled Super gameboy which outputs the border.

**Comment by ThreepwoodLeBrush** [comment]
Yep, that was the "scaling issue". Thanks a lot, it was on by default and I did not notice.

However the controls in Alleyway are still broken, even without any input device attached (right after hitting return to load the ROM I unplugged the keyboard to test it).

**Comment by sorgelig** [comment]
will be fixed soon

**Comment by sorgelig** [comment]
SGB is disable by default now.
