### ISSUE TITLE
Gameboy Scaling Not following VSCALE Option

### ISSUE THREAD

**Issue by Ashenshards** [MiSTer-devel/Gameboy_MiSTer#78]
Super Gameboy : Off, or Pallette
Scandoubler Fx: (some option enabled.)

results in appropriately sized screen according to vscale_mode.

Super Gameboy: Off, or Pallete
Scandouble Fx: Off

results in screen larger than TV. Image is cut off. 

Super Gameboy : On
Scandoubler Fx: Off

results in appropriately integer scaled screen as well as slightly smaller for 'border' allowance.

In short : Only way that GB core will follow my ini setting is with some scandoubler effect enabled. 
Seems strange behaviour, but other users have also reported. I'd like to use chosen scaling without scandouble option if possible. also seems strange that Super Gameboy option with fit to screen option first fits to screen, then some ms later exceeds the screen. As it should make it smaller. 

Edit = Not VSYNC , intended vscale_mode.

**Comment by sorgelig** [comment]
this is not an issue actually.
Integer option just use largest integer scaling according to current resolution which is different between scandoubled or non-scandoubled, sgb enabled and sgb disabled.
