### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by frederic-mahe** [MiSTer-devel/Gameboy_MiSTer#8]
Hi,

I don't know if you are familiar with [mooneye-gb](https://github.com/Gekkio/mooneye-gb), but that project offers a suite of small `.gb` ROMs carefully designed to check wether or not emulators can reproduce the exact behavior of real Gameboys.

Here is a [direct link](https://gekkio.fi/files/mooneye-gb/latest/) to the test suite.

**Comment by brNX** [comment]
Thanks, I'm closing this one . Tests like these were/are heavily used, wilbertpol's, blargg's and liji32's (samesuite). The next step would be to automate those and check for regressions 😉
