### ISSUE TITLE
Final Fantasy Adventure name entry no cursor

### ISSUE THREAD

**Issue by henryrizzi** [MiSTer-devel/Gameboy_MiSTer#80]
In Final Fantasy Adventure (md5: 24cd3bdf490ef2e1aa6a8af380eccd78) the name entry screen is broken as there's no cursor behind the letters on the screen. I've tried the official gbc bios and the dmg bios and the behavior remains the same.
Is this a known issue? If it helps to replicate, this is with the 128mb ram module installed.

**Comment by SegaSnatcher** [comment]
New commit fixed this issue.

**Comment by henryrizzi** [comment]
Yes it did. Awesome work on all these fixes from @brNX and @paulb-nl ! ❤️
