### ISSUE TITLE
GB: Super Hunchback (J) [!].gb timing/line errors in the intro

### ISSUE THREAD

**Issue by brNX** [MiSTer-devel/Gameboy_MiSTer#84]
![20200622_190035-Super Hunchback (J)  !](https://user-images.githubusercontent.com/407195/85325448-8d45b680-b4c3-11ea-96d3-0d8904a2e1b2.png)

**Comment by paulb-nl** [comment]
I found the problem. Actually SCX is not supposed to be latched at the beginning of rendering. The Gameboy adds the current pixel count and SCX to get the tilemap address. So this means you can change scroll during the line but only per tile. SCX[2:0] is only used at the start of rendering when it skips pixels for fine scrolling.

I saw this behavior on videos of Super Mario Land where sometimes only a few tiles of the flickering top line were scrolled incorrectly. 

The word "Super" at the top of the screen in Super Hunchback still flickers sometimes. I don't know if that is accurate to hardware. The rest of the flickering lines are gone. Super Mario Land still seems to have more flickering than a real Gameboy but I am not sure.

**Comment by brNX** [comment]
Great!!

I spend a few hours today chasing my tail with the interrupt_time.gb testrom , only to find out that it doesn't pass on a DMG too 😄  ... 

I can confirm that the "SUPER" flickers from time to time on real hardware (tested on GBC), the same with the first and last few rows of the flipping "HUNCHBACK" text.

The first line of the of the text on top of super mario land also flickers from time to time on original hardware when scolling.

Tomorrow I'll focus on the Halt bug

**Comment by brNX** [comment]
Fixed in #91
