### ISSUE TITLE
 Chikyuu Kaihou Gun ZAS:   Whole screen flickers

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/Gameboy_MiSTer#85]
The previous core didn't flicker, but it also didn't have the 2nd scrolling layer.   

The new fixes added the 2nd scrolling layer, but now the whole image is constantly flickering.

**Comment by paulb-nl** [comment]
It looks like it is supposed to be like this. The Gameboy's LCD slow pixel response time would have blended the 2 layers together. A frame blend feature is needed for this.

**Comment by brNX** [comment]
> It looks like it is supposed to be like this. The Gameboy's LCD slow pixel response time would have blended the 2 layers together. A frame blend feature is needed for this.

I can confirm this, both BGB and Sameboy need mix last and current frame/frame blending enabled so it doesn't flicker.

**Comment by SegaSnatcher** [comment]
So basically like the feature on the GBA core?   Is it possible to port that implementation or would GB require something different?

**Comment by wwark** [comment]
I tested another games we have flickering but found them also on YT videos for BGB for example.

* "batlle ping pong" (during the selection of the country)
* "batlle doge ball" on the sprites of the players.

Do you think it is related to this issue ?

**Comment by brNX** [comment]
> I tested another games we have flickering but found those flickering on YT videos for BGB for example.
> 
> * "batlle ping pong" (during the selection of the country)
> * "batlle doge ball" on the sprites of the players.
> 
> Do you think it is related to this issue ?

battle ping pong definitely is, battle dodge ball has glitchy/flickering sprites even on original hardware

**Comment by SegaSnatcher** [comment]
Frameblending feature fixes this issue.  Thanks Paul
