### ISSUE TITLE
[GB] Bomber Man Collection (Japan) (SGB Enhanced) - Not able to launch a game selected

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#90]
Hi,
This rom is 1Mo size.
There is 3 bomberman games available in this collection.

When we select a game one of 3 games, the game seems to reboot and propose again the 3 games.

Thanks,

**Comment by brNX** [comment]
According to BGB this ones uses the MBC1M mapper with multicart support, it hasn't been implemented yet.

https://gbdev.gg8.se/wiki/articles/Memory_Bank_Controllers#Multicart_MBCs

> MBC1M uses the MBC1 IC, but the board does not connect the MBC1's A18 address output to the ROM. This allows including multiple 2 Mbit (16 bank) games, with SRAM bank select ($4000) to select which of up to four games is switched in. In theory, a MBC1M board could be made for 1 Mbit or 512 kbit games by additionally not connecting A17 and A16 outputs, but this appears not to have been done in licensed games.

**Comment by wwark** [comment]
It is like GBA so many different carttriges and specific addons.

**Comment by paulb-nl** [comment]
The header of these is the same as a normal MBC1 so we need to detect them by game id or add a manual option. I think it is only 3 games or so?

**Comment by brNX** [comment]
> The header of these is the same as a normal MBC1 so we need to detect them by game id or add a manual option. I think it is only 3 games or so?

yes, according to gekkio https://forums.nesdev.com/viewtopic.php?f=20&t=14099&sid=fb2054baac7b6a46fa7a53e2ed1022dc#p168728 and here on sameboy mbc1 apparently has 3 types of wiring https://github.com/LIJI32/SameBoy/blob/ef203cf0e5b6dd1e9ee5da47b0827b0ef132fa02/Core/mbc.c#L147  here is where he attempts to guess the wiring https://github.com/LIJI32/SameBoy/blob/ef203cf0e5b6dd1e9ee5da47b0827b0ef132fa02/Core/mbc.c#L150

besides bomberman collection I only know of mortal kombat 1+2

**Comment by wwark** [comment]
In this PDF, https://gekkio.fi/files/gb-docs/gbctr.pdf p39.
There is this description.

> Detecting multicartsMBC1 multicarts are not detectable by simply looking at the ROM header, because the ROM type value is justone of the normal MBC1 values. However, detection is possible by going through BANK2 values and lookingat "bank 0" of each multicart game and doing some heuristics based on the header data. All the includedgames, including the game selection menu, have proper header data. One example of a good heuristic is logodata verification.So, if you have a 8 Mbit cart with MBC1, first assume that it’s a multicart and bank numbers are 6-bitvalues. Set BANK1 to zero and loop through the four possible BANK2 values while checking the data at0x0104-0x0133. In other words, check logo data starting from physical ROM locations0x00104,0x40104,0x80104, and0xC0104. If proper logo data exists with most of the BANK2 values, the cart is most likely amulticart. Note that multicarts can just have two actual games, so one of the locations might not have theheader data in place.

**Comment by wwark** [comment]
Thanks @paulb-nl !
It is fixed in this PR https://github.com/MiSTer-devel/Gameboy_MiSTer/pull/117
