### ISSUE TITLE
[GB] Card Game (Japan) - Issue to start the game

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#92]
In the mister, we are not able to start this game the button "A, B and start" are not effective.
There is just the button select working, we can go from "1 player to 2 player, to other selection" in the menu.

I tried the same rom in BGB and we can select "1 player" with the start button and go to next selection menu.

Thanks,

**Comment by brNX** [comment]
Thanks for reporting this one , seems like something is off on the "fake" link port, when enabling "Link Port" in the OSD the buttons start to work

**Comment by wwark** [comment]
Thank you for your answer. It means we need to enable "Link Port" for this game or it will possible to start this game by a fix in the future without enable "link" ?
The option "Link" is to used a link gameboy with the snac adapter am I correct ?

**Comment by brNX** [comment]
yes, this should be fixed in the future

**Comment by wwark** [comment]
Fixed by #113

Thanks @paulb-nl !
