### ISSUE TITLE
[GB] Games (HuC1) stuck after the nintendo logo

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Gameboy_MiSTer#93]
Found those games stuck after Nintendo logo (roms tested on BGB without this issue) 

- Chousoku Spinner (Japan) (SGB Enhanced) (Sha1 : 057a3251bbb7eb4e04b01f786bd2986af5eabc58)
- Daikaijuu Monogatari - The Miracle of the Zone (Japan) (SGB Enhanced) (Sha1 : 44cafcb56f470881b67e57c0649afbc638cda136)
- Daikaijuu Monogatari - The Miracle of the Zone II (Japan) (SGB Enhanced) (GB Compatible).gbc (Sha1: 7bf6e2d7fc58e8abe61785e413bcf4150fa8bee5)

Thanks,

**Comment by brNX** [comment]
Thanks for reporting these, cases like this are usually very helpful

**Comment by brNX** [comment]
Both use the HuC1 mapper which isn't implemented yet

**Comment by wwark** [comment]
Thank you for this information.
I closed this ticket.

Do you have the list of mapper not implemented on the Gameboy Core for not report them ?

**Comment by brNX** [comment]
you can leave it open just add a reference to HuC1 in the title. The  Huc1, MBC1M and MMM01 among others haven't been implemented yet, some of the HuC1 games apparently use a IR sensor and MBC7 (kirby's tilt'n' tumble uses accelerometers )

**Comment by wwark** [comment]
Ok I reopened it thank you !

**Comment by wwark** [comment]
Thanks @paulb-nl ! I tried your update to add Huc1 mapper it working great.
I can play now Pocket BomberMan !

**Comment by paulb-nl** [comment]
@wwark I have also added MBC7 and if you have an analog joystick then you can play Kirby Tilt 'n' Tumble 🎉

**Comment by wwark** [comment]
I saw it ! I compiled the change ! Need to connect an analog joystick !

**Comment by wwark** [comment]
Thanks again @paulb-nl
