### ISSUE TITLE
Feature request - Support built-in SGB2 borders

### ISSUE THREAD

**Issue by mario-64** [MiSTer-devel/Gameboy_MiSTer#94]
On a real Super Gameboy 2, games which do not have their own border are assigned a default one which resembles an original Gameboy. See below:
![SGB2](https://user-images.githubusercontent.com/5170184/86376107-869e0880-bc54-11ea-9380-7ffcbe38f131.jpg)

The current MiSTer GB core does not do this so if you have SGB enabled you end up with a tiny gameplay window and no explanation as to why. We should match behavior of the actual hardware. If a game does not have its own defined border we should display the default one.  

Additionally, real SGB2 includes several built-in borders for games which don't have their own. These borders even have their own animations. 

See https://www.youtube.com/watch?v=JU5OBrDlOR8 starting at the 5:13 mark for in-depth border behavior on real SGB hardware. 
See https://www.youtube.com/watch?v=JCjJAcM6hI8 for an overview of all built-in SGB2 borders

If our goal with MiSTer is hardware accuracy, SGB behavior should fully match real hardware (with the exception of features which require a SNES which I know it cannot do). With SGB enabled a border should _always_ be shown (unless palette mode) and the user should be able to change to any of the other built-in borders.

I think this would be a great addition and BIG thanks to the devs for their hard work on this core.

**Comment by birdybro** [comment]
Adding this here in case it helps, attached is every single Super GameBoy border in PNG form. Potentially, any of them which don't work for whatever reason could be achieved with an overlay and mapping to that ROM, or just the sgb built-in ones could be brought in as overlays at some point for games that don't have their own SGB border.

https://mega.nz/file/BmxWkARI#dF0I-8fC7C4_MgAKgVgArsGkfNxiBczJ2fLB13XyhKg

**Comment by birdybro** [comment]
![Super Game Boy 2 PCB Border](https://user-images.githubusercontent.com/16388068/112220979-8089f680-8bec-11eb-93ad-ebabb593e990.png)
![Super Game Boy 1 Border](https://user-images.githubusercontent.com/16388068/112220981-8089f680-8bec-11eb-9ce6-ea27f3fcf822.png)
![Super Game Boy 2 Border](https://user-images.githubusercontent.com/16388068/112220982-8089f680-8bec-11eb-8737-fe14c049a1c5.png)

The original ones that i found on VGMuseum were inaccurate screenshots. I ripped new ones myself and made now they are proper 224p images. :)

**Comment by paulb-nl** [comment]
I have added a Load SGB Border option to the core.

It loads .sgb files which contain:
0x0000-0x1FFF: Tiles. Size 8192 bytes
0x2000-0x26FF: Tile map. Size 1792 bytes
0x2700-0x277F: Palettes. Size 128 bytes

borders as 256x224 .png files can be converted to tile data with `superfamiconv` https://github.com/Optiroc/SuperFamiconv

@birdybro: your last borders are offset 1 pixel vertically and the SGB2 ones have transparency on the sides. Only the middle 160x144 part should be transparent. I have corrected that and was able to convert them with:

````
superfamiconv -v --color-zero #00000000 --in-image border.png --out-palette snes.palette --out-tiles snes.tiles --out-map snes.map --out-tiles-image tiles.png
````
The output from superfamiconv needs to be padded to the sizes needed in the .sgb file stated above and combined.

Attached are the 3 borders converted to .sgb format and the modified core for testing.

When a new Main Mister is released the core will get auto loading of border and palette at boot.

[sgb_borders.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/6214378/sgb_borders.zip)

[Gameboy_sgb_border.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/6214379/Gameboy_sgb_border.zip)

**Comment by birdybro** [comment]
Very cool thank you so much!!

The first ones I posted I realized later were 223p not 224p so I generated the next ones via using bsnes and doing a screenshot from there. That might explain the issue. I did transparency on the sides kind of as a habit as they were just black screen anyways, but good call. Thanks again!

**Comment by SparkmanDesigns** [comment]
Fantastic! Thanks for giving your time to this non-essential feature. It's completely superfluous but it adds so much joy to the SGB experience! Can't wait to try it.

**Comment by Kitrinx** [comment]
This is a great use for that new persistent file loaded feature like NES palettes now have. Palettes can also be quickly converted to that too just by adding a letter if you're updating things.

**Comment by paulb-nl** [comment]
@Kitrinx Yeah, I haven't added it to this build yet because it doesn't work with the current released Main but I will add it to borders and palettes.

Btw I didn't think of the word persistent. FP would have been a better option name than FC :)

**Comment by paulb-nl** [comment]
It is also possible to extract borders using Memory Tools of Mesen-S.  Debug->Memory Tools.

With the border visible copy the following data:

View: Video RAM - 0000-1FFF: Tiles 8192 bytes
View: Video RAM - 7800-7EFF: Tile map 1792 bytes
View: CG RAM - 0080-00FF: Palette 128 bytes

**Comment by paulb-nl** [comment]
Here are some more borders: 
[sgb_borders2.zip](https://github.com/MiSTer-devel/Gameboy_MiSTer/files/6222151/sgb_borders2.zip)

**Comment by mankeli** [comment]
Thanks for this! So much nicer to play on CRT when the borders are not just black :)

**Comment by Toryalai1** [comment]
Please close this issue
